# Generated by Django 3.0.4 on 2020-04-14 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200411_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 7, 31, 15, 891350, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
